---
- hosts: localhost

  collections:
  - netapp.ontap

  vars_files:
    - creds.yml
    - vars.yml

  #module_defaults:
  #  group/netapp.ontap:
  #    hostname: "{{ hostname }}"
  #    username: "{{ username }}"
  #    password: "{{ password }}"
  #    https: true
  #    validate_certs: false

  tasks:
  - name: info gather
    na_ontap_rest_info:
      subset: volume_info
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
