version: 3

dependencies: 
  galaxy: requirements.yml

images: 
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:1.0.0-775

options:
  package_manager_path: /usr/bin/microdnf
