version: 3

dependencies:
  galaxy:
    collections:
      - ansible.utils
      - netapp.ontap
      - community.windows

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf
