version: 3

dependencies:
  galaxy:
    collections:
      - netapp.ontap

images: 
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:1.0.0-720

options:
  package_manager_path: /usr/bin/microdnf
